platform :ios, '10.0'

workspace 'jitsi-meet'

target 'jitsi-meet' do
  project 'app/app.xcodeproj'

  pod 'Crashlytics', '~> 3.12.0'
  pod 'Fabric', '~> 1.9.0'
  pod 'Firebase/Core', '~> 5.18.0'
  pod 'Firebase/DynamicLinks', '~> 5.18.0'
end

target 'JitsiMeet' do
  project 'sdk/sdk.xcodeproj'

  # React Native and its dependencies
  #

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # React Native plugins
  #

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'
  pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'
  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNWatch', :path => '../node_modules/react-native-watch-connectivity'
  
  # 추가 외부 라이브러리
  # pod 'lottie-ios', '~> 3.0.3'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  # pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker/react-native-orientation-locker.podspec'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNSketchCanvas', :path => '../node_modules/@terrylinla/react-native-sketch-canvas'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RCTRestart', :path => '../node_modules/react-native-restart'

  # 로컬 라이브러리
  pod 'react-native-fast-image', :path => './modules/react-native-fast-image'

  # Native pod dependencies
  #

  pod 'Amplitude-iOS', '~> 4.0.4'
  pod 'ObjectiveDropboxOfficial', '~> 3.9.4'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'YES'
    end
  end
end
