platform :ios, '11.0'
workspace 'wehago-meet'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
install! 'cocoapods', :deterministic_uuids => false

target 'WehagoMeet' do
  project 'app/app.xcodeproj'

  pod 'Firebase/Analytics', '~> 6.33.0'
  pod 'Firebase/Crashlytics', '~> 6.33.0'
  pod 'Firebase/DynamicLinks', '~> 6.33.0'
end

target 'JitsiMeetSDK' do
  project 'sdk/sdk.xcodeproj'

  # React Native and its dependencies
  #

  pod 'FBLazyVector', :path => '../node_modules/react-native/Libraries/FBLazyVector/'
  pod 'FBReactNativeSpec', :path => '../node_modules/react-native/Libraries/FBReactNativeSpec/'
  pod 'RCTRequired', :path => '../node_modules/react-native/Libraries/RCTRequired/'
  pod 'RCTTypeSafety', :path => '../node_modules/react-native/Libraries/TypeSafety/'
  pod 'React', :path => '../node_modules/react-native/'
  pod 'ReactCommon', :path => '../node_modules/react-native/ReactCommon', :subspecs => [
    'turbomodule'
  ]
  pod 'React-Core', :path => '../node_modules/react-native/', :subspecs => [
    'CoreModulesHeaders',
    'DevSupport',
    'RCTWebSocket'
  ]
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # React Native plugins
  #

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'
  pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'
  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNWatch', :path => '../node_modules/react-native-watch-connectivity'
  pod 'RNDefaultPreference', :path => '../node_modules/react-native-default-preference'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


    # 추가 외부 라이브러리
    # pod 'lottie-ios', :path => '../node_modules/lottie-ios'
    pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
    # pod 'RNSVG', :path => '../node_modules/react-native-svg'
    pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker/react-native-orientation-locker.podspec'
    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
    pod 'RNSketchCanvas', :path => '../node_modules/@terrylinla/react-native-sketch-canvas'
    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
    pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
    pod 'RCTRestart', :path => '../node_modules/react-native-restart'
    pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'
    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
    pod 'RNLocalize', :path => '../node_modules/react-native-localize'
    pod 'RNExitApp', :path => '../node_modules/react-native-exit-app'
    pod 'jail-monkey', :path => '../node_modules/jail-monkey'
    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
    pod 'ReactNativeIncallManager', :path => '../node_modules/react-native-incall-manager'
    pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'
    pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
    pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'
    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
    pod 'RNScreens', :path => '../node_modules/react-native-screens'
    pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'
    pod 'RNCClipboard', :path => '../node_modules/@react-native-clipboard/clipboard'
    pod 'react-native-bluetooth-status', :path => '../node_modules/react-native-bluetooth-status'
  # Native pod dependencies
  #

  pod 'CocoaLumberjack', '~>3.5.3'
  pod 'ObjectiveDropboxOfficial', '~> 3.9.4'

  use_native_modules!
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['SUPPORTS_MACCATALYST'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
